backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'depositions'
    label: 'depoimentos'
    format: 'json'
    folder: 'content/depositions'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Contato', name: 'contact', widget: 'string' }
      - { label: 'Depoimento', name: 'testimony', widget: 'markdown' }
  - name: 'statistics'
    label: 'estatisticas'
    format: 'json'
    folder: 'content/statistics'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Percentual', name: 'percent', widget: 'number' }
      - { label: 'Descricao', name: 'description', widget: 'string' }
  - name: 'partners'
    label: 'parceiros'
    format: 'json'
    folder: 'content/partners'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Nome', name: 'name', widget: 'string' }
      - { label: 'Logo', name: 'logo', widget: 'image' }
      - { label: 'Link', name: 'link', widget: 'string' }