backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'depositions'
    label: 'depoimentos'
    format: 'json'
    folder: 'content/depositions'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Contato', name: 'contact', widget: 'string' }
      - { label: 'Depoimento', name: 'testimony', widget: 'markdown' }
